export enum LocationEvent {

    LOCATION_UPDATE = "LOCATION_UPDATE",
    LOCATION_ERROR = "LOCATION_ERROR",
    LOCATION_PERMISSION_DENIED = "LOCATION_PERMISSION_DENIED",
    ZONE_ENTERED = "ZONE_ENTERED",
    ZONE_EXITED = "ZONE_EXITED"

}